import { Artists } from './artists';

export const Filteredartists:Artists[] = [
{id:7,name:"Kalidas Jayaram",picture:"kalidas.jpg",age:25,	desc:"Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book.",tag:"Actor",websites:"http://kalidas.com"},
{id:8,name:"Mohanlal",picture:"lal.jpg",age:55,desc:"Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book.",tag:"Actor",websites:"http://mohanlal.com"},
{id:9,name:"Mammootty",picture:"mammootty.jpg",age:65,desc:"Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book.",tag:"Actor",websites:"http://mammotty.com"},
{id:10,name:"Prithviraj",picture:"prithvi.jpg",age:35,desc:"Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book.",tag:"Actor",websites:"http://prithviraj.com"},
{id:11,name:"Dulquer Salman",picture:"dulquer.jpg",age:35,desc:"Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book.",tag:"Actor",websites:"http://dq.com"},
{id:12,name:"Asif Ali",picture:"asif.jfif",age:32,desc:"Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book.",tag:"Actor",websites:"http://asifali.com"},
{id:13,name:"Fahad Fasil",picture:"fahad.jpg",age:33,desc:"Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book.",tag:"Actor",websites:"http://fahad.com"},
{id:14,name:"Kalidas Jayaram",picture:"kalidas.jpg",age:25,desc:"Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book.",tag:"Actor",websites:"http://kalidas.com"}

];